anand/urls.py
from django.urls import path

from anand.views import *

app_name = 'an_dude'

urlpatterns = [
    path('coder/',coder,name='coder'),
]

lokesh/urls.py
from django.urls import path
from lokesh.views import *

app_name = 'lok_dude'

urlpatterns = [
    path('saviour/',saviour,name='saviour'),
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
import anand,lokesh
from sameer.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('anand/',include('anand.urls')),
    path('lokesh/',include('lokesh.urls')),
    path('flutter/',flutter,name='flutter'),
]

anand/models.py
from django.db import models

# Create your models here.

lokesh/models.py
from django.db import models

# Create your models here.

sameer/models.py
from django.db import models

# Create your models here.

anand/views.py
from django.shortcuts import render

# Create your views here.
def coder(request):
    return render(request,'coder.html')

lokesh/views.py
from django.shortcuts import render

# Create your views here.

def saviour(request):
    return render(request,'saviour.html')

sameer/views.py
from django.shortcuts import render

# Create your views here.
def flutter(request):
    return render(request,'flutter.html')

templates/coder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Using door for facewash</h3>
    <h4>Eat code,Drink code,Sleep after code</h4>
    <h3>Mawa going to tour</h3>
    <a href="{% url 'flutter' %}"><h3>Ask to sallu bhai</h3></a>
</body>
</html>

templates/flutter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>making girl as frd with short period of time</h3>
    <h3>mawa what to tour </h3>
    <a href="{% url 'lok_dude:saviour' %}"><h3>Ask to saviour</h3></a>
</body>
</html>

templates/saviour.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>The saviour from the faculty</h3>
    <h3>The details gainer</h3>
    <h3>lets rock the tour'😄😃</h3>
    <a href="{% url 'an_dude:coder' %}"><h3>lets go to tour</h3></a>
</body>
</html>